---

- name: mkdir ansible cache
  file: path={{ ansible_cache_dir }} state=directory owner=root group=root mode=0655

# Get Deb

- name: Zabbix Common - Get DEB - Debian 7
  get_url: dest={{ ansible_cache_dir }}/zabbix-release_2.0-1.deb url=http://repo.zabbix.com/zabbix/2.0/debian/pool/main/z/zabbix-release/zabbix-release_2.0-1wheezy_all.deb
  when: ansible_os_family == 'Debian' and ansible_distribution_version.split('.')[0]|int == 7
  tags: zabbix-common

- name: Zabbix Common - Get DEB - Ubuntu 12.04
  get_url: dest={{ ansible_cache_dir }}/zabbix-release_2.0-1.deb url=http://repo.zabbix.com/zabbix/2.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.0-1precise_all.deb
  when: ansible_os_family == 'Ubuntu' and ansible_distribution_release == 'precise'
  tags: zabbix-common

# Install Deb

- name: Zabbix Common - Install DEB
  shell: dpkg -i {{ ansible_cache_dir }}/zabbix-release_2.0-1.deb
  tags: zabbix-common

# Update Cache 

- name: Zabbix Common - Update APT Cache
  apt: update-cache=yes
  tags: zabbix-common
