---
# Install Nginx, PHP5 (PHP-FPM), And Fcgiwrap
# http://www.howtoforge.com/perfect-server-debian-wheezy-nginx-bind-dovecot-ispconfig-3-p4

- name: Install Nginx
  apt: pkg=$item state=installed
  with_items:
    - nginx

- name: Install PHP5 (PHP-FPM), And Fcgiwrap
  apt: pkg=$item state=installed
  with_items:
    - php5-fpm 
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-ming
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-snmp
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - memcached
    - php-apc
    - fcgiwrap

- name: Configure PHP w/ NGinx - fix_pathinfo
  lineinfile: dest=/etc/php5/fpm/php.ini
              state=present
              regexp='^cgi\.fix_pathinfo'
              line='cgi.fix_pathinfo=0'
              backup=yes
  notify:
    - restart nginx
    - reload php5-fpm

- name: Configure PHP w/ NGinx - timezone
  lineinfile: dest=/etc/php5/fpm/php.ini
              state=present
              regexp='^date\.timezone'
              line='date.timezone="Europe/Paris"'
              backup=yes
  notify:
    - restart nginx
    - reload php5-fpm
