---
# Defines tasks applicable across all machines in the infrastructure.

- name: Install Nginx
  apt: pkg=$item state=installed
  with_items:
    - nginx

- name: Install PHP
  apt: pkg=$item state=installed
  with_items:
    - php5-fpm 
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-intl
    - php-pear
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-ming
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-snmp
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - memcached
    - php-apc
    - fcgiwrap

