---
# Defines tasks applicable across all machines in the infrastructure.

- name: Install base pkgs
  apt: pkg=$item state=installed
  with_items:
    - vim
    - htop
    - git
    - encfs
    - libfuse-dev
    - tig
    - byobu
    - build-essential
    - etckeeper
    - unzip
    - unrar

- include: security.yml tags=security
